export default {
  GOOGLE_WORKSPACE_CLI_TOKEN: "",
  GOOGLE_WORKSPACE_CLI_CREDENTIALS_FILE: "",
  GOOGLE_WORKSPACE_CLI_CLIENT_ID: "",
  GOOGLE_WORKSPACE_CLI_CLIENT_SECRET: "",
  GOOGLE_WORKSPACE_CLI_CONFIG_DIR: "",
  GOOGLE_WORKSPACE_PROJECT_ID: "",
  GMAIL_DEFAULT_USER_ID: "me",
  GMAIL_PUBSUB_TOPIC: ""
};
