export default {
  X_COOKIES: "",
  X_CHAT_PASSCODE: "",
  CHROME_EXECUTABLE_PATH: "",
  HEADLESS: "true",
  EXPECTED_ACCOUNT_HANDLE: "",
  MIN_SECONDS_BETWEEN_SENDS: "90",
  MAX_SENDS_PER_DAY: "20",
  MAX_SENDS_PER_CAMPAIGN_PER_DAY: "20",
  MIN_SECONDS_BETWEEN_FOLLOWS: "300",
  MAX_FOLLOWS_PER_DAY: "20",
  OPERATION_TIMEOUT_MS: "120000"
};
