export default {
  HEADLESS: "true",
  PHONE_NUMBER: "",
  DEFAULT_COUNTRY_CODE: "",
  SEND_DELAY_MS: "1200",
  HUMANIZE_SEND: "true",
  HUMANIZE_SEND_INITIAL_DELAY_MS: "5000",
  HUMANIZE_SEND_ONLINE_LEAD_MS: "1500",
  HUMANIZE_SEND_POST_SEND_ONLINE_MS: "2500",
  HUMANIZE_SEND_TYPING_MS: "0",
  HUMANIZE_SEND_MAX_MS: "60000",
  INBOX_POLL_SECONDS: "15",
  READY_TIMEOUT_MS: "120000",
  JOB_TIMEOUT_MS: "120000",
  IDLE_SHUTDOWN_MS: "300000",
  CHROME_EXECUTABLE_PATH: ""
};
