export default {
  HEADLESS: "true",
  PHONE_NUMBER: "",
  DEFAULT_COUNTRY_CODE: "54",
  SEND_DELAY_MS: "1200",
  INBOX_POLL_SECONDS: "15",
  READY_TIMEOUT_MS: "120000",
  JOB_TIMEOUT_MS: "120000",
  IDLE_SHUTDOWN_MS: "300000",
  CHROME_EXECUTABLE_PATH: ""
};
